export interface CustomerCylinderLedger {
  id?: number;
  customerId: number;
  customerName: string;
  variantId: number;
  variantName: string;
  transactionDate: string;
  refType: string;
  refId: number;
  filledOut: number;
  emptyIn: number;
  balance: number;
  transactionReference?: string;
  paymentMode?: string;
  totalAmount?: number;
  amountReceived?: number;
  dueAmount?: number;
  updateReason?: string;
  bankAccountId?: number;
  bankAccountName?: string;
  bankAccountNumber?: string;
  fromWarehouseName?: string;
  toWarehouseName?: string;
  createdAt?: string;
  updatedDate?: string;
  createdBy?: string;
  updatedBy?: string;
  note?: string;
}
